# Question number 1 




In [1]:
class Country():
    def __init__(self, CName, CPopulation, SqMile):
        self.CName = CName
        self.CPopulation = CPopulation
        self.SqMile = SqMile

    def Density(self):
        return self.CPopulation / self.SqMile

    def Record(self):
        self.CName = input("Enter the country name: ")
        self.CPopulation = int(input("Enter the population: "))
        self.SqMile = int(input("Enter the Square Mile: "))

    def __str__(self):
        return f"{self.CName} {self.CPopulation} {self.SqMile}"


c = Country("Nepal", 328000, 3774)

density = c.Density()

c.Record()

print("The country is", c.CName)
print("The Population is ", c.CPopulation)
print("The squareMile is ", c.SqMile)
print("The density is ", c.Density())





        

Enter the country name: india
Enter the population: 300000
Enter the Square Mile: 300
The country is india
The Population is  300000
The squareMile is  300
The density is  1000.0


# Question number 2


In [2]:
class Rectangle():
    def __init__(self, length, width):
        self.length = length
        self.width = width
    
    def rectangle_area(self):
        return self.length*self.width


newRectangle = Rectangle(12,10)
area = newRectangle.rectangle_area()


print("The area of the Rectangle is ", newRectangle.rectangle_area())


The area of the Rectangle is  120


# Question number 3

In [5]:
import numpy as np

A = np.arange(10)
A





array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Question 3 a)

In [6]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Question 3 b)

In [7]:
A[-1]

9

#### Question 3 c)

In [8]:
A[::2]

array([0, 2, 4, 6, 8])

# Question 4

In [9]:
B = np.arange(0, 12).reshape(3,4)

# (a) extract first and second columns
first_second_cols = B[:, :2]
print("First and second columns:\n", first_second_cols)

# (b) extract first and second rows
first_second_rows = B[:2, :]
print("First and second rows:\n", first_second_rows)

# (c) extract specific array from B
specific_array = B[1:, 2:]
print("Extracted array:\n", specific_array)



First and second columns:
 [[0 1]
 [4 5]
 [8 9]]
First and second rows:
 [[0 1 2 3]
 [4 5 6 7]]
Extracted array:
 [[ 6  7]
 [10 11]]


# Question number 5 

#### Question 5 a)

The output of A:
    
    array([[[0, 1]],
            [[2, 3]],
            [[4, 5]],
            [[6, 7]]])
    
The output of B:
    
        array([[[0],
                [1]],
                [[2],
                [3]],
                [[4],
                [5]],
                [[6],
                [7]]])


#### Question 5 b)

Here, A and B have cannot be directly added because they have different dimensions. Both of them need to undergo 
Broadcasting i.e. 1 is added to each of the missing dimension and missing elements are filled
with duplicates of the values contained in extended sizes.

After Broadcasting, A:

array(
        [[
        
        [0, 1],
        [0, 1]],
        
        [[2, 3],
        [2, 3]],
        
        [[4, 5],
        [4, 5]],
        
        [[6, 7],
        [6, 7]
        
        ]]
        
        )

After Broadcasting, B:
    
array([[

        [0, 0],
        [1, 1]],
        
        [[2, 2],
        [3, 3]],
        
        [[4, 4],
        [5, 5]],
        
        [[6, 6],
        [7, 7]
        
        ]])

Now, the corresponding elements of A and B are added. 
The output of A + B:
    
array(
        [[
        
        [ 0, 1],
        [ 1, 2]],
        
        [[ 4, 5],
        [ 5, 6]],
        
        [[ 8, 9],
        [ 9, 10]],
        
        [[12, 13],
        [13, 14]
        
        ]])

#### Question 5 c)

As I have mentioned it before, A and B undergo Broadcasting then they are subtracted.

The output of A - B:
    
array([[
        
        [ 0, 1],
        [-1, 0]],
        
        [[ 0, 1],
        [-1, 0]],
        
        [[ 0, 1],
        [-1, 0]],
        
        [[ 0, 1],
        [-1, 0]]]
        
       )


#### Question 5 d)

The output of A * B:
array([[
        
        [ 0, 0],
        [ 0, 1]],
        
        [[ 4, 6],
        [ 6, 9]],
        
        [[16, 20],
        [20, 25]],
        
        [[36, 42],
        [42, 49]]])

As mentioned earlier, both A and B undergo Broadcasting.